# NumPy 

[NumPy](https://docs.scipy.org/doc/numpy/user/quickstart.html) é uma biblioteca python para operações de algebra linear. É uma ferramenta poderosa e importante no âmbito da ciência de dados devido às suas funcionalidades e por servir de ferramenta base para a construções de várias outras bibliotecas.

## Vamos importar

In [2]:
import numpy as np

# Numpy Arrays

### Criando numpy arrays a partir de listas

In [3]:
lista = [1,2,3] #lista em python
lista

[1, 2, 3]

In [4]:
np.array(lista) # um numpy array

array([1, 2, 3])

In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix) # uma matriz numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Métodos

### arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## eye
matriz identidade

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Criando arrays randômicos

### rand

In [14]:
np.random.rand(2)

array([0.10175164, 0.10637552])

In [15]:
np.random.rand(5,5)

array([[0.95714605, 0.42305524, 0.74985294, 0.75034565, 0.35252659],
       [0.42618286, 0.88260239, 0.23422227, 0.9847981 , 0.4328793 ],
       [0.41564064, 0.00882724, 0.27931109, 0.02716164, 0.79388604],
       [0.34637995, 0.29223643, 0.63252016, 0.9362208 , 0.93202365],
       [0.41273482, 0.25919431, 0.97058224, 0.55261594, 0.50891534]])

### randn

In [16]:
np.random.randn(2)

array([-0.49179668, -0.46970815])

In [17]:
np.random.randn(5,5)

array([[-0.52875551, -0.88195351, -0.80873135, -0.38027277, -0.70474754],
       [-1.34381804,  0.58616289,  1.44099019, -0.32009046,  1.25224566],
       [ 0.4199468 , -0.29231147, -0.45232829,  0.81133464,  0.21807907],
       [-1.92636616,  0.95379608, -1.06890655, -1.27843095,  0.02570913],
       [-0.68963573, -0.02596396, -2.36156054,  0.09094848,  1.0898652 ]])

### randint
Retorna valores aletórios interios a partir de `low` (inclusive) até `high` (exclusivo).

In [18]:
np.random.randint(1,100)

83

In [19]:
np.random.randint(1,100,10)

array([91, 44, 52, 35, 47, 58, 15, 51, 57, 55])

=========================================================================================

In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([39, 45,  3, 35, 19,  8, 49, 46, 26,  2])

## Reshape

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max min argmax e argmin


In [24]:
ranarr

array([39, 45,  3, 35, 19,  8, 49, 46, 26,  2])

In [25]:
ranarr.max()

49

In [26]:
ranarr.argmax()

6

In [27]:
ranarr.min()

2

In [28]:
ranarr.argmin()

9

## Shape

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25).shape

(1, 25)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [34]:
arr.dtype

dtype('int32')

# NumPy Operations

## Aritmética

In [80]:
arr = np.arange(0,10)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [83]:
arr / arr

C:\Users\cleilton_rocha\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [86]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [88]:
np.log(arr)

C:\Users\cleilton_rocha\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# NumPy Indexação e seleção

In [89]:
arr = np.arange(0,11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Obtendo elementos do array

In [46]:
arr[8]

8

In [47]:
#Slice
arr[1:5]

array([1, 2, 3, 4])

In [48]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
# Reiniciando array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Observe que o valor também é alterado no array original!

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Vamos agora copiar os dados originais para criar, de fato, um novo array. Assim poderemos alterá-lo sem impactar no array original

In [54]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Trabalhando com matrizes

In [55]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[1]

array([20, 25, 30])

In [57]:
arr_2d[1][0]

20

In [58]:
arr_2d[1,0]

20

In [59]:
# 2D Slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [60]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [61]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Indexação avançada

In [92]:
arr2d = np.zeros((10,10))

In [94]:
arr_length = arr2d.shape[1]
arr_length

10

In [64]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [65]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [66]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Seleção

In [67]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
bool_arr = arr>4

In [70]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])